dist: trusty
sudo: required

language:
  - rust
  - cpp

compiler:
  - gcc

rust:
  nightly

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

before_install:
  - |
   wget -O /tmp/emsdk-portable.tar.gz https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz \
   && tar xf /tmp/emsdk-portable.tar.gz -C /tmp/ \
   && /tmp/emsdk-portable/emsdk install latest 2>&1 | grep -v '^x ' && /tmp/emsdk-portable/emsdk activate latest
  - source /tmp/emsdk-portable/emsdk_env.sh

# See https://github.com/kripken/emscripten/pull/5087
  - cd /tmp/emsdk-portable
  - mkdir libstdc++
  - cd libstdc++
  - wget http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gcc-5/libstdc++6-5-dbg_5.4.1-2ubuntu1\~14.04_amd64.deb
  - ar xv libstdc++6-5-dbg_5.4.1-2ubuntu1\~14.04_amd64.deb && tar -xf ./data.tar.xz
  - cd usr/lib/
  - export LD_LIBRARY_PATH=${PWD}

  - rustup target add asmjs-unknown-emscripten
  - rustup target add wasm32-unknown-emscripten
  - cargo install --git https://github.com/paritytech/wasm-utils wasm-build

script:
  - cd fckt/wasm-tests
  - ./build.sh
